#!/bin/bash

src="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pipeline_types="$(cd $src && find . -name 'pipeline.yml' | sed -e "s|^\./||;s|/pipeline.yml$||")"

usage() {
cat << EOF
${1:-"Setup pipeline template for the desired type of pipeline."}

Usage: $0 <type> [/repo/to/setup]

where <type> is one of:
$(echo "$pipeline_types" | sed -e "s/^/  - /")

EOF
  exit ${2:-0}
}

set -e
case "${1}" in
  (-h|--help|help)
    usage
    ;;
esac

template=$1
target=${2:-$(pwd)}

[ -n ${template} ] || usage "ERROR: Missing pipeline template type" 1
[ -d ${target} ]   || usage "ERROR: ${target} path not found"       1

pattern="^($(echo "$pipeline_types" | tr "\n" "|" | sed -e "s/\|*$//"))$"
[[ "${template}"=~$pattern ]] || usage "ERROR: ${template} is not a valid pipeline template" 1

echo "Installing ${template} pipeline in ${target}..."
mkdir -p ${target}/ci
cp -R ${src}/${template}/* ${target}/ci/
cp ${src}/repipe ${target}/ci/
[ -f ${target}/ci/settings.yml ] || echo "--- {}" > ${target}/ci/settings.yml
exit 0
