---
meta:
  kit:             <kit>
  release:         <kit-descriptor>
  target:          pipes/genesis
  url:             https://pipes.scalecf.net
  iaas:            vsphere  # <aws|gcp|openstack|azure>
  exposed:         false
  initial_version: <Intended Initial Release Version>

  #upstream:
    #  An optional block describing any upstream deployment repo to pull in

    # manifests: 
    #   package: app-autoscaler
    #   repo:    cloudfoundry/app-autoscaler-release
    #   path:    upstream
    #   filter:
    #   - templates/*
    #   - operations/*

    #  An optional block describing the bosh release used for generating release notes, checking specs,
    #  and upstream release updates

    # bosh_releases      
    # - name:       app-autoscaler
    #   type:       github-release
    #   repository: cloudfoundry/app-autoscaler-release
    #   path:       overlay/releases/app-autoscaler.yml
    #   access_token: ((github.access_token))

  bosh:
    uri:      ((bosh.uri))
    username: ((bosh.username))
    password: ((bosh.password))
    cacert:   ((bosh.ca))

  vault:
    url:       ((vault.url))
    token:     ((vault.token))

  aws:
    access_key: ((aws.access_key_id))
    secret_key: ((aws.secret_access_key))

  github:
    owner:        genesis-community
    repo:         cf-genesis-kit
    branch:       develop
    main-branch:  main
    private_key:  ((github.private_key))
    access_token: ((github.access_token))
    name:         ((github.name))
    email:        ((github.email))

  shout:
    url:      ((shout.url)
    username: ((shout.username))
    password: ((shout.password))
